apiVersion: v1
kind: Pod
metadata:
  name: broken-pod
  namespace: monitoring 
  labels:
    app: broken
spec:
  containers:
    - name: broken-container
      image: invalidimagename123  # ❌ This image does not exist
  restartPolicy: Always

