{
 "title": "RummyIndus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info,pod)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "RummyKhiladi",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n  <img src=\"https://www.indusrummy.in/img/Indus-Rummy-Icon.png\" width=\"500\" height=\"155\" alt=\"Your image\">\n</div>\n"
   }
  },
  {
   "title": " Cluster-Wide Network Input (Receive) in MB/s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{interface!=\"lo\"}[5m])) / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster-Wide Network Output (Transmit) in MB/s",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{interface!=\"lo\"}[5m])) / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"}\n  -\n  node_filesystem_free_bytes{fstype!~\"tmpfs|overlay\"}\n) / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nnode_filesystem_free_bytes{fstype!~\"tmpfs|overlay\"} / 1024 / 1024 / 1024\n",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": " Memory usage per pod (in MB)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  container_memory_usage_bytes{container!=\"\", container!=\"POD\"}\n) / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage per container (in MB)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container!=\"\", container!=\"POD\"} / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " CPU usage per pod (in millicores)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod,namespace) (\n  rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\"}[5m])\n) * 1000\n",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": " CPU utilization per container (in millicores):",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, container) (\n  rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\"}[5m])\n) * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Level monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Total Number of NameSpaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Number of Node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\", status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster-level CPU usage (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster-Level-Memory Usage(%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster-Level Network Output",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo|veth.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster-Level Network Input (bytes/sec)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes/second" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo|veth.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Containers per Namespace",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(namespace)(kube_pod_container_status_running)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pod Level Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Total number of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=~\"$namespace\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  kube_pod_status_phase{phase=\"Pending\", namespace=~\"$namespace\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  kube_pod_status_phase{phase=\"Failed\", namespace=~\"$namespace\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum  (\n  kube_pod_status_phase{phase=\"Unknown\", namespace=~\"$namespace\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Restarted Pods per Node",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (\n  kube_pod_container_status_restarts_total\n  * on (pod, namespace) group_left(node)\n    kube_pod_info\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod, namespace) (kube_pod_container_status_restarts_total)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per-Pod Network Output (Transmit) in MB/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum by (pod, namespace) (\n  rate(container_network_transmit_bytes_total{interface!=\"lo\", pod!=\"\"}[5m])\n) / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Per-Pod Network Input (Receive) in MB/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 62 },
   "targets": [
    {
     "expr": "sum by (pod, namespace) (\n  rate(container_network_receive_bytes_total{interface!=\"lo\", pod!=\"\"}[5m])\n) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 7, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  kube_deployment_status_replicas{namespace=~\"$namespace\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_deployment_status_replicas{namespace=~\"$namespace\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Updated Replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}