apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: test-job
    spec:
      containers:
        - name: test
          image: busybox
          command: ["sh", "-c", "echo Running test job && sleep 5 && echo Job done"]
      restartPolicy: Never

