version: '3.8'

services:
  node-app:
    build: .
    container_name: node-app
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz-otel-collector:4317
      - OTEL_SERVICE_NAME=node-app
    ports:
      - "3001:3000"  # Change the host port to 3001
    networks:
      - signoz-network

  signoz-otel-collector:
    image: signoz/signoz-otel-collector
    container_name: signoz-otel-collector-t
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=5775
      - COLLECTOR_GRPC_PORT=4317
    ports:
      - "4319:4317"
    networks:
      - signoz-network

  signoz-frontend:
    image: signoz/signoz
    container_name: signoz-frontend
    ports:
      - "8081:3301"  # Change the host port to 8081
    networks:
      - signoz-network

networks:
  signoz-network:
    driver: bridge

